image: archlinux
packages:
  - curl
  - rsync
sources:
  - https://git.sr.ht/~janbaudisch/ghana.janbaudisch.de
secrets:
  - d2be8e67-9e75-4024-8229-0afcffd1a161
tasks:
  - setup: |
      curl -s https://paste.sr.ht/blob/da38fee5eec30fffb5f6f51d939036232bf16a84 | sh
  - build: |
      cd ghana.janbaudisch.de
      export URL=$(./deploy-url.sh)
      sed -i "s/ghana.janbaudisch.de/${URL}/g" config.toml
      hugo
  - deploy: |
      cd ghana.janbaudisch.de
      export URL=$(./deploy-url.sh)
      ~/rsync public/ $URL
