title = "Jan in Ghana"
baseURL = "https://ghana.janbaudisch.de"

languageCode = "de"
defaultContentLanguage = "de-de"
isMultilingual = false

theme = "tranquilpeak"

paginate = 10

[author]
    name = "Jan Baudisch"
    bio = "weltwärts"
    job = "Freiwilliges Jahr"
    location = "Jirapa, Ghana"
    picture = "images/profile.jpg"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
    url = "/"

[[menu.main]]
    weight = 2
    identifier = "donate"
    name = "Spenden"
    pre = "<i class=\"sidebar-button-icon fas fa fa-money\"></i>"
    url = "/spenden"

[[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Kategorien"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
    url = "/categories"

[[menu.main]]
    weight = 4
    identifier = "tags"
    name = "Tags"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
    url = "/tags"

[[menu.misc]]
    weight = 1
    identifier = "rss"
    name = "RSS"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
    url = "/index.xml"

[[menu.misc]]
    weight = 2
    identifier = "instagram"
    name = "Instagram"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-instagram\"></i>"
    url = "https://instagram.com/janaufreisen"

[[menu.misc]]
    weight = 3
    identifier = "pixelfed"
    name = "Pixelfed"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-picture-o\"></i>"
    url = "https:/pixelfed.social/janaufreisen"

[params]
    dateFormat = "2. January 2006"

    clearReading = true

    hierarchicalCategories = false

    description = "Hugo tranquilpeak theme demo"

    sidebarBehavior = 1

    coverImage = "cover.jpg"

    imageGallery = false

    thumbnailImage = true
    thumbnailImagePosition = "left"
    autoThumbnailImage = false

    favicon = "favicon.ico"

[params.footer]
    copyright = "Jan Baudisch <a href='https://creativecommons.org/licenses/by-sa/4.0/deed.de'>CC-BY-SA 4.0</a>"
